import { useMemo, useState } from 'react';
import { CostBar } from './components/CostBar';
import { DataTable } from './components/DataTable';
import { CsvImport } from './components/CsvImport';
import { modelRecords, orderRecords, type ModelRecord } from './data/sampleData';
import { formatCurrency, orderVariance, quoteFromMargin, sumCostBuckets } from './domain/costing';
import type { ImportedModel } from './domain/csv';

type Mode = 'model' | 'order';
const Status = ({ children }: { children: string }) => <span className={children === '已审核' || children === '已完成' ? 'status approved' : 'status active'}>{children}</span>;
const ResponsiveOverrides = () => <style>{`.app-shell{max-width:100vw;overflow:hidden}.sidebar-resizer{grid-row:2;grid-column:1;justify-self:end;width:8px;height:100%;cursor:col-resize;z-index:4}.sidebar-resizer:hover{background:#0969da33}.main-content{min-width:0;overflow-x:hidden}.table-wrap{max-width:100%;overflow-x:auto}@media(max-width:1450px){.detail-grid,.order-layout{grid-template-columns:1fr}.metadata{white-space:normal}}@media(max-width:1180px){.app-shell{grid-template-columns:260px minmax(0,1fr)!important}.topbar h1{font-size:20px;margin:0 12px}.header-controls{gap:5px}.header-controls select{max-width:125px}.kpi-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:820px){.app-shell{display:block!important}.sidebar-resizer{display:none}.topbar{position:relative;height:auto;min-height:58px;flex-wrap:wrap}.brand-mark{width:58px;height:58px}.topbar h1{font-size:17px;flex:1}.header-controls{width:100%;order:3;padding:8px;overflow-x:auto}.header-controls .search{width:180px;flex:0 0 auto}.sidebar{max-height:280px;overflow:auto;border-right:0;border-bottom:1px solid #dbe5f0}.main-content{padding:16px;overflow-x:auto}.title-row{display:block}.metadata{text-align:left;line-height:1.7;margin-top:8px}.kpi-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.kpi.quote{grid-column:span 2}.cost-composition{display:block}.cost-bar{overflow-x:auto;height:70px}.cost-bar>div{min-width:130px}.bar-total{display:none}}@media(max-width:480px){.topbar h1{font-size:15px}.header-controls select{display:none}.header-controls .search{width:145px}.main-content{padding:12px}.kpi-grid{gap:7px}.kpi{padding:11px;min-height:84px}.kpi strong{font-size:18px}.title-row h2{font-size:19px}.data-panel h3{font-size:14px}}`}</style>;
const GridPlacement = () => <style>{`.sidebar{grid-column:1;grid-row:2}.main-content{grid-column:2;grid-row:2}@media(max-width:820px){.sidebar,.main-content{grid-column:auto;grid-row:auto}}`}</style>;

export default function App() {
  const buildStamp = '2026-08-14-pages-refresh';
  const [mode, setMode] = useState<Mode>('model');
  const [selectedModel, setSelectedModel] = useState(modelRecords[0].id);
  const [selectedOrder, setSelectedOrder] = useState(orderRecords[0].id);
  const [query, setQuery] = useState('');
  const [sidebarWidth, setSidebarWidth] = useState(340);
  const [imported, setImported] = useState<ImportedModel[]>([]);
  const models = useMemo(() => [...modelRecords, ...imported.map((record) => ({ ...record, valve: 'CSV 导入版本', updated: '本次导入', materialLines: modelRecords[0].materialLines, laborLines: modelRecords[0].laborLines, outsourceLines: modelRecords[0].outsourceLines, overheadLines: modelRecords[0].overheadLines } as ModelRecord))], [imported]);
  const activeModel = models.find((record) => record.id === selectedModel) ?? models[0];
  const activeOrder = orderRecords.find((record) => record.id === selectedOrder) ?? orderRecords[0];
  const filteredModels = models.filter((record) => `${record.model} ${record.version}`.toLowerCase().includes(query.toLowerCase()));
  const filteredOrders = orderRecords.filter((record) => `${record.id} ${record.customer} ${record.model}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="app-shell" data-build={buildStamp} style={{ gridTemplateColumns: `${sidebarWidth}px minmax(0, 1fr)` }}><ResponsiveOverrides /><GridPlacement />
    <header className="topbar"><div className="brand-mark">⚓</div><h1>船用低温阀门成本核算工作台</h1><div className="header-controls"><select aria-label="筛选字段"><option>产品型号</option><option>订单编号</option></select><label className="search"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={mode === 'model' ? '请输入产品型号 / 版本' : '请输入订单号 / 客户'} />⌕</label><select aria-label="版本"><option>版本：全部</option></select><select aria-label="核算期间"><option>核算期间：2026-08</option></select><CsvImport onImport={(records) => { setImported(records as ImportedModel[]); setSelectedModel((records as ImportedModel[])[0]?.id ?? selectedModel); }} /></div></header>
    <aside className="sidebar"><div className="mode-tabs"><button className={mode === 'model' ? 'selected' : ''} onClick={() => setMode('model')}>型号成本</button><button className={mode === 'order' ? 'selected' : ''} onClick={() => setMode('order')}>订单执行</button></div>{mode === 'model' ? <ModelSidebar records={filteredModels} selected={activeModel.id} onSelect={setSelectedModel} /> : <OrderSidebar records={filteredOrders} selected={activeOrder.id} onSelect={setSelectedOrder} />}</aside><div className="sidebar-resizer" role="separator" aria-label="调整左侧栏目宽度" onPointerDown={(event) => { const start = event.clientX; const width = sidebarWidth; const move = (pointer: PointerEvent) => setSidebarWidth(Math.max(240, Math.min(460, width + pointer.clientX - start))); const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); }} />
    <main className="main-content">{mode === 'model' ? <ModelView model={activeModel} /> : <OrderView order={activeOrder} />}</main>
  </div>;
}

function ModelSidebar({ records, selected, onSelect }: { records: ModelRecord[]; selected: string; onSelect: (id: string) => void }) { const groups = records.reduce<Record<string, ModelRecord[]>>((all, item) => { (all[item.model] ??= []).push(item); return all; }, {}); return <><h2>产品与版本</h2><div className="side-search">⌕ 搜索产品型号 / 版本 <span>⚱</span></div><nav>{Object.entries(groups).map(([model, items]) => <div className="model-group" key={model}><div className="model-label">⌄　▣　{model}</div>{items.map((item) => <button key={item.id} className={`record ${selected === item.id ? 'current' : ''}`} onClick={() => onSelect(item.id)}><span>⌄　 {item.version}</span><Status>{item.status}</Status></button>)}</div>)}</nav><p className="side-foot">共 {records.length} 个成本版本</p></>; }
function OrderSidebar({ records, selected, onSelect }: { records: typeof orderRecords; selected: string; onSelect: (id: string) => void }) { return <><h2>生产订单</h2><div className="side-search">⌕ 搜索订单号 / 客户 <span>⚱</span></div><nav>{records.map((item) => <button key={item.id} className={`record order-record ${selected === item.id ? 'current' : ''}`} onClick={() => onSelect(item.id)}><strong>{item.id}</strong><small>{item.customer}</small><span>{item.model} · {item.quantity} 台</span><Status>{item.status}</Status></button>)}</nav><p className="side-foot">共 {records.length} 个订单</p></>; }
function Kpi({ label, value, share, emphasis }: { label: string; value: number; share?: string; emphasis?: boolean }) { return <div className={`kpi ${emphasis ? 'quote' : ''}`}><span>{label}（RMB）</span><strong>{formatCurrency(value)}</strong>{share && <small>占比　{share}</small>}</div>; }
function ModelView({ model }: { model: ModelRecord }) { const buckets = { material: model.material, labor: model.labor, outsource: model.outsource, overhead: model.overhead }; const total = sumCostBuckets(buckets); const quote = quoteFromMargin(total, model.margin) ?? 0; return <><section className="title-row"><div><h2>{model.model} <span>·</span> {model.version}</h2><p>{model.valve}</p></div><div className="metadata">核算期间：2026-08　 币种：RMB　 汇率：1.0000　 版本状态：<Status>{model.status}</Status>　 支持订单继承与变更　 最后更新：{model.updated}</div></section><section className="kpi-grid"><Kpi label="材料成本" value={model.material} share={`${(model.material / total * 100).toFixed(2)}%`} /><Kpi label="直接人工" value={model.labor} share={`${(model.labor / total * 100).toFixed(2)}%`} /><Kpi label="外协与质量" value={model.outsource} share={`${(model.outsource / total * 100).toFixed(2)}%`} /><Kpi label="制造费用" value={model.overhead} share={`${(model.overhead / total * 100).toFixed(2)}%`} /><Kpi label="建议报价" value={quote} emphasis /></section><CostBar buckets={buckets} /><QuotePanel cost={total} margin={model.margin} /><section className="detail-grid"><DataTable title="BOM材料明细" lines={model.materialLines} kind="material" /><DataTable title="工艺与人工" lines={model.laborLines} kind="labor" /><DataTable title="外协与质量" lines={model.outsourceLines} kind="outsource" /><DataTable title="制造费用分摊" lines={model.overheadLines} kind="overhead" /></section></>; }
function QuotePanel({ cost, margin }: { cost: number; margin: number }) { const [currency, setCurrency] = useState<'RMB'|'USD'>('RMB'); const [rate, setRate] = useState(7.25); const [buffer, setBuffer] = useState(0.02); const [exportCost, setExportCost] = useState(380); const rmb = quoteFromMargin(cost, margin) ?? 0; const usd = ((cost + exportCost) / (rate * (1 - buffer))) / (1 - margin); return <section className="quote-panel"><div><h3>报价方案</h3><button className={currency==='RMB'?'selected':''} onClick={()=>setCurrency('RMB')}>人民币报价</button><button className={currency==='USD'?'selected':''} onClick={()=>setCurrency('USD')}>美元报价</button></div>{currency==='RMB'?<strong>RMB 建议报价：¥ {formatCurrency(rmb)}</strong>:<div className="usd-quote"><label>报价汇率<input aria-label="报价汇率" type="number" step="0.01" value={rate} onChange={e=>setRate(Number(e.target.value))}/></label><label>汇率缓冲<input type="number" step="0.01" value={buffer} onChange={e=>setBuffer(Number(e.target.value))}/></label><label>出口附加成本（RMB）<input type="number" value={exportCost} onChange={e=>setExportCost(Number(e.target.value))}/></label><strong>USD 建议报价：$ {formatCurrency(usd)}</strong><small>贸易条款：FOB｜成本底稿：RMB 完全成本｜历史汇率须随报价版本冻结</small></div>}</section>; }
function OrderView({ order }: { order: typeof orderRecords[number] }) { const variance = orderVariance(order.standard, order.actual); const gross = order.revenue - order.actual; return <><section className="title-row"><div><h2>订单执行成本 <span>·</span> {order.id}</h2><p>{order.customer}　 {order.model}　 {order.quantity} 台　交付：{order.delivery}</p></div><div className="metadata">初始版本：{order.initialVersion}　 当前版本：{order.currentVersion}　 订单状态：<Status>{order.status}</Status></div></section><section className="kpi-grid order-kpis"><Kpi label="当前标准总成本" value={order.standard} /><Kpi label="实际总成本" value={order.actual} /><Kpi label="成本差异" value={variance.amount} share={`${(variance.rate * 100).toFixed(2)}%`} /><Kpi label="销售收入" value={order.revenue} /><Kpi label="订单毛利" value={gross} share={`${(gross / order.revenue * 100).toFixed(2)}%`} emphasis /></section><section className="order-layout"><section className="data-panel actual-panel"><h3>订单实际成本明细</h3><div className="table-wrap"><table><thead><tr><th>类别</th><th>项目</th><th>标准金额（RMB）</th><th>实际金额（RMB）</th><th>差异（RMB）</th><th>差异原因</th></tr></thead><tbody>{order.actualLines.map((line) => <tr key={line.item}><td>{line.category}</td><td>{line.item}</td><td>{formatCurrency(line.standard)}</td><td>{formatCurrency(line.actual)}</td><td className={line.actual > line.standard ? 'negative' : 'positive'}>{formatCurrency(line.actual - line.standard)}</td><td>{line.reason}</td></tr>)}</tbody><tfoot><tr><td colSpan={2}>合计</td><td>{formatCurrency(order.standard)}</td><td>{formatCurrency(order.actual)}</td><td>{formatCurrency(variance.amount)}</td><td>-</td></tr></tfoot></table></div></section><section className="timeline"><h3>版本变更记录</h3>{order.changes.length ? order.changes.map((change) => <article key={change.date}><time>{change.date}</time><strong>{change.from} → {change.to}</strong><p>{change.reason}</p><small>标准成本影响：+{formatCurrency(change.impact)}　操作人：{change.operator}</small></article>) : <p className="empty">该订单未发生版本切换，按初始锁定版本执行。</p>}<div className="audit-note">初始版本永久保留，当前版本用于现行标准成本；所有实际成本均可追溯至订单明细。</div></section></section></>; }
